# Generated by Django 4.0.4 on 2022-05-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio/static/portfolio/images'),
        ),
    ]
