# Generated by Django 4.0.4 on 2022-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('rank', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=130)),
                ('ects', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('linkedIn', models.URLField()),
            ],
        ),
    ]
