# Generated by Django 4.0.4 on 2022-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='linkedIn',
            field=models.URLField(blank=True, default=''),
        ),
    ]
