# Generated by Django 4.0.4 on 2022-05-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_course_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.AlterField(
            model_name='course',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
