# Generated by Django 4.0.4 on 2022-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graf', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
