# Generated by Django 4.0.4 on 2022-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_quizz_delete_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='pictures/')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(related_name='Course', to='portfolio.person'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='graf',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
