# Generated by Django 4.0.4 on 2022-05-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_picture_alter_course_professor_alter_quizz_graf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quizz',
        ),
    ]
