# Generated by Django 4.0.4 on 2022-05-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_course_docente_teorica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='docente_teorica',
        ),
    ]
