# Generated by Django 4.0.4 on 2022-05-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_remove_course_docente_teorica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='portfolio.person'),
        ),
    ]
