# Generated by Django 4.0.4 on 2022-06-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_alter_project_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
